version: "3.9"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "getme-bd-dev"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "@getME653%"
    ports:
      - "5432:5432"
    volumes:
      - get-me-dev:/var/lib/postgresql/data
volumes:
  get-me-dev:
