server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/getme-bd-dev
    username: root
    password: "@getME653%"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 200000
      maximum-pool-size: 10
      connection-timeout: 30000
      pool-name: default-pool
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC
    hibernate:
      ddl-auto: none

