spring:
  profiles:
    active: ${APP_PROFILE:dev}
  security:
    client-id: ${CLIENT_ID:getme}
    client-secret: ${CLIENT_SECRET:getme653}
    jwt:
      duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

aws:
  s3:
    access-key-id: ${S3_KEY_ID}
    secret-access-key: ${S3_SECRET_KEY}