spring:
  profiles:
    active: ${APP_PROFILE:dev}
  security:
    client-id: ${CLIENT_ID:getme}
    client-secret: ${CLIENT_SECRET:getme653}
    jwt:
      duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}